import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Repository root (one level above tools/). */
export const ROOT = resolve(__dirname, '..');

/** Master SVG source directory: icons/<variant>/<category>/<name>.svg */
export const ICONS_SRC = resolve(ROOT, 'icons');

/**
 * Destination for all generated TypeScript. This is the `lib` folder of the
 * `@zellavora/icons/generated` secondary entry point. Never hand-edit these files.
 */
export const GENERATED_DIR = resolve(ROOT, 'generated/lib');

/**
 * The full set of supported icon variants. Adding one here is the single
 * source of truth consumed by the generator, types, and the component.
 */
export const ICON_VARIANTS = [
  'outline',
  'filled',
  'rounded',
  'sharp',
  'duotone',
  'brand',
  'flag',
  'emoji',
  'animated',
] as const;

export type IconVariant = (typeof ICON_VARIANTS)[number];

/** The canonical viewBox every normalized icon is expected to expose. */
export const CANONICAL_VIEWBOX = '0 0 24 24';

/** Default stroke width normalization target for stroke-based variants. */
export const CANONICAL_STROKE_WIDTH = 2;

export const AUTOGEN_BANNER = `/**
 * DO NOT EDIT — this file is generated by the @zellavora/icons pipeline.
 * Run \`npm run icons:generate\` (or \`zv-icons generate\`) to refresh it.
 */
`;

export function isIconVariant(value: string): value is IconVariant {
  return (ICON_VARIANTS as readonly string[]).includes(value);
}
